const Routes = {
  LOADING: 'LOADING',

  LOGIN_STACK: 'LOGIN_STACK',
  MAIN_APP: 'MAIN_APP', // DRAWER

  APP_INTRO: 'APP_INTRO',

  HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
  HOME_TABS: 'HOME_TABS', // HOME TABS

  HOME_SCREEN: 'HOME',
  ACTIVITIES_SCREEN: 'ACTIVITIES',
  BOOKS_SCREEN: 'BOOKS',
  MAP_SCREEN: 'MAP',
  PROFILE_SCREEN: 'PROFILE',
  SECURITY_SCREEN:'SECURITY_SCREEN',
  INITIAL_SCREEN:'INITIAL_SCREEN'
}

export default Routes
